  int num1 = 15;
  int num2 = 30; 
  int num3;
Console.WriteLine("Before Swapping:");
Console.WriteLine("Num 1: " + num1 + " Num 2: " + num2);
num3 = num1;
num1 = num2;
num2 = num3;
Console.WriteLine("After Swapping:");
Console.WriteLine("Num 1: " + num1 + " Num 2: " + num2);